/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openepi.weather.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import io.openepi.weather.WeatherJSON;

/**
 * Parameters with validity times over one hour. Will not exist for all time steps.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-12T08:53:23.751911+02:00[Europe/Oslo]", comments = "Generator version: 7.13.0")
public class ForecastTimeStepDataNext1Hours {
  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  @javax.annotation.Nonnull
  private ForecastTimePeriod details;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  @javax.annotation.Nonnull
  private ForecastSummary summary;

  public ForecastTimeStepDataNext1Hours() {
  }

  public ForecastTimeStepDataNext1Hours details(@javax.annotation.Nonnull ForecastTimePeriod details) {
    this.details = details;
    return this;
  }

  /**
   * Get details
   * @return details
   */
  @javax.annotation.Nonnull
  public ForecastTimePeriod getDetails() {
    return details;
  }

  public void setDetails(@javax.annotation.Nonnull ForecastTimePeriod details) {
    this.details = details;
  }


  public ForecastTimeStepDataNext1Hours summary(@javax.annotation.Nonnull ForecastSummary summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nonnull
  public ForecastSummary getSummary() {
    return summary;
  }

  public void setSummary(@javax.annotation.Nonnull ForecastSummary summary) {
    this.summary = summary;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStepDataNext1Hours forecastTimeStepDataNext1Hours = (ForecastTimeStepDataNext1Hours) o;
    return Objects.equals(this.details, forecastTimeStepDataNext1Hours.details) &&
        Objects.equals(this.summary, forecastTimeStepDataNext1Hours.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, summary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStepDataNext1Hours {\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("details");
    openapiFields.add("summary");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("details");
    openapiRequiredFields.add("summary");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ForecastTimeStepDataNext1Hours
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ForecastTimeStepDataNext1Hours.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ForecastTimeStepDataNext1Hours is not found in the empty JSON string", ForecastTimeStepDataNext1Hours.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ForecastTimeStepDataNext1Hours.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ForecastTimeStepDataNext1Hours` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ForecastTimeStepDataNext1Hours.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `details`
      ForecastTimePeriod.validateJsonElement(jsonObj.get("details"));
      // validate the required field `summary`
      ForecastSummary.validateJsonElement(jsonObj.get("summary"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ForecastTimeStepDataNext1Hours.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ForecastTimeStepDataNext1Hours' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ForecastTimeStepDataNext1Hours> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ForecastTimeStepDataNext1Hours.class));

       return (TypeAdapter<T>) new TypeAdapter<ForecastTimeStepDataNext1Hours>() {
           @Override
           public void write(JsonWriter out, ForecastTimeStepDataNext1Hours value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ForecastTimeStepDataNext1Hours read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ForecastTimeStepDataNext1Hours given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ForecastTimeStepDataNext1Hours
   * @throws IOException if the JSON string is invalid with respect to ForecastTimeStepDataNext1Hours
   */
  public static ForecastTimeStepDataNext1Hours fromJson(String jsonString) throws IOException {
    return WeatherJSON.getGson().fromJson(jsonString, ForecastTimeStepDataNext1Hours.class);
  }

  /**
   * Convert an instance of ForecastTimeStepDataNext1Hours to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return WeatherJSON.getGson().toJson(this);
  }
}

