/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openepi.weather.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.openepi.weather.model.ForecastMeta;
import io.openepi.weather.model.ForecastTimeStep;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.openepi.weather.JSON;

/**
 * Forecast
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-12T08:53:23.751911+02:00[Europe/Oslo]", comments = "Generator version: 7.13.0")
public class Forecast {
  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  @javax.annotation.Nonnull
  private ForecastMeta meta;

  public static final String SERIALIZED_NAME_TIMESERIES = "timeseries";
  @SerializedName(SERIALIZED_NAME_TIMESERIES)
  @javax.annotation.Nonnull
  private List<ForecastTimeStep> timeseries = new ArrayList<>();

  public Forecast() {
  }

  public Forecast meta(@javax.annotation.Nonnull ForecastMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @javax.annotation.Nonnull
  public ForecastMeta getMeta() {
    return meta;
  }

  public void setMeta(@javax.annotation.Nonnull ForecastMeta meta) {
    this.meta = meta;
  }


  public Forecast timeseries(@javax.annotation.Nonnull List<ForecastTimeStep> timeseries) {
    this.timeseries = timeseries;
    return this;
  }

  public Forecast addTimeseriesItem(ForecastTimeStep timeseriesItem) {
    if (this.timeseries == null) {
      this.timeseries = new ArrayList<>();
    }
    this.timeseries.add(timeseriesItem);
    return this;
  }

  /**
   * Get timeseries
   * @return timeseries
   */
  @javax.annotation.Nonnull
  public List<ForecastTimeStep> getTimeseries() {
    return timeseries;
  }

  public void setTimeseries(@javax.annotation.Nonnull List<ForecastTimeStep> timeseries) {
    this.timeseries = timeseries;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Forecast forecast = (Forecast) o;
    return Objects.equals(this.meta, forecast.meta) &&
        Objects.equals(this.timeseries, forecast.timeseries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, timeseries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Forecast {\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    timeseries: ").append(toIndentedString(timeseries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("meta");
    openapiFields.add("timeseries");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("meta");
    openapiRequiredFields.add("timeseries");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Forecast
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Forecast.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Forecast is not found in the empty JSON string", Forecast.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Forecast.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Forecast` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Forecast.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `meta`
      ForecastMeta.validateJsonElement(jsonObj.get("meta"));
      // ensure the json data is an array
      if (!jsonObj.get("timeseries").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `timeseries` to be an array in the JSON string but got `%s`", jsonObj.get("timeseries").toString()));
      }

      JsonArray jsonArraytimeseries = jsonObj.getAsJsonArray("timeseries");
      // validate the required field `timeseries` (array)
      for (int i = 0; i < jsonArraytimeseries.size(); i++) {
        ForecastTimeStep.validateJsonElement(jsonArraytimeseries.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Forecast.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Forecast' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Forecast> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Forecast.class));

       return (TypeAdapter<T>) new TypeAdapter<Forecast>() {
           @Override
           public void write(JsonWriter out, Forecast value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Forecast read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Forecast given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Forecast
   * @throws IOException if the JSON string is invalid with respect to Forecast
   */
  public static Forecast fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Forecast.class);
  }

  /**
   * Convert an instance of Forecast to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

