/*
 * Agriculture API
 * This API is used to get aggregated data from Deforestation, Flood, Weather and Soil APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openepi.agriculture.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets models.PeakTimingEnum
 */
@JsonAdapter(ModelsPeakTimingEnum.Adapter.class)
public enum ModelsPeakTimingEnum {
  
  BB("BB"),
  
  GC("GC"),
  
  GB("GB");

  private String value;

  ModelsPeakTimingEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ModelsPeakTimingEnum fromValue(String value) {
    for (ModelsPeakTimingEnum b : ModelsPeakTimingEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ModelsPeakTimingEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final ModelsPeakTimingEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ModelsPeakTimingEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ModelsPeakTimingEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ModelsPeakTimingEnum.fromValue(value);
  }
}

