/*
 * Soil API
 * This is a RESTful service that provides soil information based on data sourced from <a href=\"https://www.isric.org/explore/soilgrids\">SoilGrids</a>. <br/>The data are freely available for use under the <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY 4.0 license</a>.
 *
 * The version of the OpenAPI document: 0.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openepi.soil.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.openepi.soil.model.SoilTypeProbability;
import io.openepi.soil.model.SoilTypes;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.openepi.soil.JSON;

/**
 * SoilTypeInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T14:23:35.781423+02:00[Europe/Oslo]", comments = "Generator version: 7.7.0")
public class SoilTypeInfo {
  public static final String SERIALIZED_NAME_MOST_PROBABLE_SOIL_TYPE = "most_probable_soil_type";
  @SerializedName(SERIALIZED_NAME_MOST_PROBABLE_SOIL_TYPE)
  private SoilTypes mostProbableSoilType;

  public static final String SERIALIZED_NAME_PROBABILITIES = "probabilities";
  @SerializedName(SERIALIZED_NAME_PROBABILITIES)
  private List<SoilTypeProbability> probabilities;

  public SoilTypeInfo() {
  }

  public SoilTypeInfo mostProbableSoilType(SoilTypes mostProbableSoilType) {
    this.mostProbableSoilType = mostProbableSoilType;
    return this;
  }

  /**
   * The most probable soil type at the queried location
   * @return mostProbableSoilType
   */
  @javax.annotation.Nonnull
  public SoilTypes getMostProbableSoilType() {
    return mostProbableSoilType;
  }

  public void setMostProbableSoilType(SoilTypes mostProbableSoilType) {
    this.mostProbableSoilType = mostProbableSoilType;
  }


  public SoilTypeInfo probabilities(List<SoilTypeProbability> probabilities) {
    this.probabilities = probabilities;
    return this;
  }

  public SoilTypeInfo addProbabilitiesItem(SoilTypeProbability probabilitiesItem) {
    if (this.probabilities == null) {
      this.probabilities = new ArrayList<>();
    }
    this.probabilities.add(probabilitiesItem);
    return this;
  }

  /**
   * Get probabilities
   * @return probabilities
   */
  @javax.annotation.Nullable
  public List<SoilTypeProbability> getProbabilities() {
    return probabilities;
  }

  public void setProbabilities(List<SoilTypeProbability> probabilities) {
    this.probabilities = probabilities;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoilTypeInfo soilTypeInfo = (SoilTypeInfo) o;
    return Objects.equals(this.mostProbableSoilType, soilTypeInfo.mostProbableSoilType) &&
        Objects.equals(this.probabilities, soilTypeInfo.probabilities);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(mostProbableSoilType, probabilities);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoilTypeInfo {\n");
    sb.append("    mostProbableSoilType: ").append(toIndentedString(mostProbableSoilType)).append("\n");
    sb.append("    probabilities: ").append(toIndentedString(probabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("most_probable_soil_type");
    openapiFields.add("probabilities");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("most_probable_soil_type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SoilTypeInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SoilTypeInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SoilTypeInfo is not found in the empty JSON string", SoilTypeInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SoilTypeInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SoilTypeInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SoilTypeInfo.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `most_probable_soil_type`
      SoilTypes.validateJsonElement(jsonObj.get("most_probable_soil_type"));
      if (jsonObj.get("probabilities") != null && !jsonObj.get("probabilities").isJsonNull()) {
        JsonArray jsonArrayprobabilities = jsonObj.getAsJsonArray("probabilities");
        if (jsonArrayprobabilities != null) {
          // ensure the json data is an array
          if (!jsonObj.get("probabilities").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `probabilities` to be an array in the JSON string but got `%s`", jsonObj.get("probabilities").toString()));
          }

          // validate the optional field `probabilities` (array)
          for (int i = 0; i < jsonArrayprobabilities.size(); i++) {
            SoilTypeProbability.validateJsonElement(jsonArrayprobabilities.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SoilTypeInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SoilTypeInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SoilTypeInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SoilTypeInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<SoilTypeInfo>() {
           @Override
           public void write(JsonWriter out, SoilTypeInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SoilTypeInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SoilTypeInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SoilTypeInfo
   * @throws IOException if the JSON string is invalid with respect to SoilTypeInfo
   */
  public static SoilTypeInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SoilTypeInfo.class);
  }

  /**
   * Convert an instance of SoilTypeInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

