name: Semantic Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'tests/**'

jobs:
  checks:
    uses: ./.github/workflows/continous-integration.yaml

  semantic-release:
    name: Semantic Release
    needs: [checks] # Ensure checks completes successfully before publishing
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for semantic-release to analyze commits

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '11'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: SERVER_USERNAME # env variable for username in deploy
          server-password: SERVER_PASSWORD # env variable for token in deploy
          gpg-private-key: GPG_PRIVATE_KEY # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Install dependencies
        run: npm ci

      # Creates tags and a release
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for the release and tag creation
          SERVER_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

